package banksAPIparsing;

import java.util.HashMap;
import java.util.Map;

public class Currencies {
    public static Map<String, Integer> currs = new HashMap<>(115);

    static {
        currs.put("USD",840);
        currs.put("EUR",978);
        currs.put("RUB",643);
        currs.put("UAH",980);
        currs.put("CHF",756);
        currs.put("CNY",156);
        currs.put("AED",784);
        currs.put("AFN",971);
        currs.put("AMD",51);
        currs.put("AOA",973);
        currs.put("ARS",32);
        currs.put("AUD",36);
        currs.put("AZN",944);
        currs.put("CAD",124);
        currs.put("CZK",203);
        currs.put("BDT",50);
        currs.put("BGN",975);
        currs.put("BHD",48);
        currs.put("BIF",108);
        currs.put("BND",96);
        currs.put("BOB",68);
        currs.put("BRL",986);
        currs.put("BWP",72);
        currs.put("BYN",933);
        currs.put("CDF",976);
        currs.put("CLP",152);
        currs.put("COP",170);
        currs.put("CRC",188);
        currs.put("CUP",192);
        currs.put("DJF",262);
        currs.put("DKK",208);
        currs.put("DZD",12);
        currs.put("EGP",818);
        currs.put("ETB",230);
        currs.put("GEL",981);
        currs.put("GHS",936);
        currs.put("GMD",270);
        currs.put("GNF",324);
        currs.put("HKD",344);
        currs.put("HRK",191);
        currs.put("HUF",348);
        currs.put("IDR",360);
        currs.put("INR",356);
        currs.put("IQD",368);
        currs.put("IRR",364);
        currs.put("ISK",352);
        currs.put("JOD",400);
        currs.put("KES",404);
        currs.put("KGS",417);
        currs.put("KHR",116);
        currs.put("KPW",408);
        currs.put("KRW",410);
        currs.put("KWD",414);
        currs.put("KZT",398);
        currs.put("LAK",418);
        currs.put("LBP",422);
        currs.put("LKR",144);
        currs.put("LYD",434);
        currs.put("MAD",504);
        currs.put("MDL",498);
        currs.put("MGA",969);
        currs.put("MKD",807);
        currs.put("MNT",496);
        currs.put("MUR",480);
        currs.put("MWK",454);
        currs.put("MXN",484);
        currs.put("MYR",458);
        currs.put("MZN",943);
        currs.put("NAD",516);
        currs.put("NGN",566);
        currs.put("NIO",558);
        currs.put("NPR",524);
        currs.put("NZD",554);
        currs.put("OMR",512);
        currs.put("PEN",604);
        currs.put("PHP",608);
        currs.put("PKR",586);
        currs.put("PYG",600);
        currs.put("QAR",634);
        currs.put("RON",946);
        currs.put("RSD",941);
        currs.put("SAR",682);
        currs.put("SCR",690);
        currs.put("SDG",938);
        currs.put("SGD",702);
        currs.put("SLL",694);
        currs.put("SOS",706);
        currs.put("SRD",968);
        currs.put("SYP",760);
        currs.put("SZL",748);

        currs.put("GBP",826);
        currs.put("ILS",376);
        currs.put("JPY",392);
        currs.put("NOK",578);
        currs.put("PLZ",985);
        currs.put("SEK",752);
        currs.put("LEK",8);

        currs.put("BTC",0);
    }

}
